### ISSUE TITLE
Receiving 'io.grpc.StatusRuntimeException: CANCELLED' when performing integration tests.

### ISSUE THREAD

**Issue by YehorPytomets** [Java-Classes/Qualifications#28]
### What is the version of gRPC?
1.28.1

### What is the version of Spine?
1.6.0

### What is the version of Java?
1.8.0_261

### What is the version of grpc-netty?
1.33.1

### What is the problem?
I receive the following errors after each integration test when shutting down the server.
```
Nov 16, 2020 4:43:21 PM io.spine.client.DeliveringMultiEventObserver lambda$nullToDefault$0
SEVERE: Error receiving event.
io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Nov 16, 2020 4:43:21 PM io.spine.client.DeliveringMultiEventObserver lambda$nullToDefault$0
SEVERE: Error receiving event.
io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Nov 16, 2020 4:43:21 PM io.spine.client.DeliveringMultiEventObserver lambda$nullToDefault$0
SEVERE: Error receiving event.
io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### What did you do?
1. Run the test `AddQualificationProfilesCommandTest#addNewProfile()`: [source code](https://github.com/Java-Classes/Qualifications/blob/test%2Fadd-profile-integration-test/server/src/test/java/com/teamdev/qualifications/server/AddQualificationProfilesCommandTest.java).
2. Test successfully finishes.
3. Errors appear when the statement `server.shutdownAndWait();` of the `@AfterEach` hook of the [`IntergrationTest`](https://github.com/Java-Classes/Qualifications/blob/test%2Fadd-profile-integration-test/server/src/test/java/com/teamdev/qualifications/server/IntegrationTest.java) is triggered.

### What do you expect?
Receive `NO_ERROR` status instead of `CANCELLED`.
Terminate the server with no errors.

### Source code:
The [branch](https://github.com/Java-Classes/Qualifications/tree/test/add-profile-integration-test), where the error happened. The [PR](https://github.com/Java-Classes/Qualifications/pull/27) of that branch.
Server: [`QualificationsServer`](https://github.com/Java-Classes/Qualifications/blob/test%2Fadd-profile-integration-test/server/src/main/java/com/teamdev/qualifications/server/QualificationsServer.java).
Client: [`QualificationsTestClient`](https://github.com/Java-Classes/Qualifications/blob/test%2Fadd-profile-integration-test/server/src/test/java/com/teamdev/qualifications/server/given/QualificationsTestClient.java).
Integration test: [`IntegrationTest`](https://github.com/Java-Classes/Qualifications/blob/test%2Fadd-profile-integration-test/server/src/test/java/com/teamdev/qualifications/server/IntegrationTest.java).

**Comment by YehorPytomets** [comment]
### SOLVED
### What did you change?
Use `QualificationsServer#shutdown()` instead of `QualificationsServer#shutdownAndWait()` in the `IntergrationTest#shutDown()`.
### What is the reason?
The `QualificationsServer#shutdownAndWait` uses internally `GrpcContainer#shutdownNowAndWait()`, which waits for the server to become terminated. Whereas the server keeps running and doesn't terminate until the client's waiting timeout is not reached. Further, the server terminates with `CANCELLED` error status.
